from enum import Enum


class AccessLevel(Enum):
    READ = "READ"
    WRITE = "WRITE"
    ADMIN = "ADMIN"


class RequestStatus(Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    MANAGER_REVIEW = "MANAGER_REVIEW"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    APPROVED = "APPROVED"
    READY_FOR_PROVISIONING = "READY_FOR_PROVISIONING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class UserRole(Enum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"
    IT_ADMIN = "IT_ADMIN"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class SystemType(Enum):
    GITHUB = "GITHUB"
    DATABASE = "DATABASE"
    DASHBOARD = "DASHBOARD"
    CRM = "CRM"
    SUPPORT = "SUPPORT"
    CLOUD = "CLOUD"
    ADMIN_PANEL = "ADMIN_PANEL"
    PRODUCTIVE_DATABASE = "PRODUCTIVE_DATABASE"
    OTHER = "OTHER"